name: dispatch-workflow
on:
    repository_dispatch:
    pull_request:
        branches: [ main ]
jobs:
  long-sleep-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Long Wait Step (1000 ms)
        run: sleep 10
